on:
  release:
    types:
      - published

env:
  IMAGE: ghcr.io/vincent-herlemont/bats-tools

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          docker build . -t ${IMAGE}
      - name: Publish
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username phanatic --password-stdin
          docker push ${IMAGE}:${RELEASE_VERSION}
          docker push ${IMAGE}:latest
