on:
  release:
    types:
      - published

env:
  IMAGE_NAME: ghcr.io/vincent-herlemont/bats-tools

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          RELEASE_DOCKER_TAG=${RELEASE_VERSION:1}
          IMAGE=${IMAGE_NAME}:${RELEASE_DOCKER_TAG}
          LATEST_IMAGE=${IMAGE_NAME}:latest
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo "LATEST_IMAGE=${LATEST_IMAGE}" >> $GITHUB_ENV
      - name: Build
        run: |
          docker build . -t ${IMAGE}
          docker build . -t ${LATEST_IMAGE}
      - name: Publish
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username phanatic --password-stdin
          docker push ${IMAGE}
          docker push ${LATEST_IMAGE}
